### ISSUE TITLE
Consider using code formatters like `black`, `ruff` or `isort` to format code base

### ISSUE THREAD

**Issue by Yevgnen** [melih-unsal/DemoGPT#10]
The title says it all...

Good formatted code base also makes contribution easier and helps keeping consistence.

**Comment by melih-unsal** [comment]
Hi @Yevgnen , 
Thank you for your suggestion, we are just adding "black" as a code formatter.

**Comment by melih-unsal** [comment]
Hey @Yevgnen ,
Thank you again for your suggestion.
We've just merged a new pr which has "black" formatter.
Now, we would be really appreciated for your contribution.

**Comment by Yevgnen** [comment]
@melih-unsal Great and thanks! Would you also consider adding tools like `isort` to format the imports?

**Comment by melih-unsal** [comment]
@Yevgnen great idea, it will also happen like the black formatter.
Let me work on it.

**Comment by Yevgnen** [comment]
Thanks!
