### ISSUE TITLE
Hope to get in touch

### ISSUE THREAD

**Issue by JimmyMa99** [melih-unsal/DemoGPT#33]
Dear [DemoGPT](https://github.com/melih-unsal/DemoGPT) developer,
Greetings! I am Jimmy, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
Jimmy

**Comment by melih-unsal** [comment]
Hi @JimmyMa99 , thank you for your invitation.  
I've just joined the channel. I'm open to all collaborations.
