### ISSUE TITLE
export the code

### ISSUE THREAD

**Issue by syberkitten** [melih-unsal/DemoGPT#40]
Amazing project and Idea!! would love to know how can I export the code
that was generated into an app, and continue developing it....

**Comment by melih-unsal** [comment]
Hi @syberkitten,
I really appreciated your attention. 

After the app is generated, code expander appears at the bottom that you can copy by pressing the copy button. The generated code and the project's requirements.txt is what you need to have a fresh start in a project. 
If you like, you can also directly edit the code by pressing the **Edit** button then **Save & Rerun** button to immidiately see the effect on the browser. 

I hope these are what you need. If not, don't hesitate to state here.
