### ISSUE TITLE
Support for custom open-ai base url

### ISSUE THREAD

**Issue by bharath97-git** [melih-unsal/DemoGPT#43]
**Is your feature request related to a problem? Please describe.**
Whenever, I would like to use a custom openAI base url such as Azure openAI or my openAI proxy, there is no option for that. DemoGPT should be able to support custom base url for openAI

**Describe the solution you'd like**
Similar to the openai API key, there should be an option to provide the open AI base url.

**Comment by melih-unsal** [comment]
Hi @bharath97-git,

Thank you for your excellent contribution! I've reviewed your pull request and found that it effectively resolves the issue of supporting custom base URLs for OpenAI services. I've gone ahead and merged it into the main codebase.

Your changes will be included in our next release, giving users the flexibility to use custom OpenAI base URLs, which is a significant improvement to DemoGPT.

Thank you again for your valuable input and for taking the time to contribute. Please feel free to reach out with any more suggestions or feedback in the future. Your contributions are highly appreciated!

Best regards,
Melih
